<a href="https://colab.research.google.com/github/prak32/Python_Assignment/blob/master/Assignment10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Q.no.1.

In [ ]:
#A.
import numpy as np
A = np.array(([1,2,3],[55,56,7]))
print(A)
try:
  A_inv = np.linalg.inv(A)
except:
  print("For inverse the martix should be square.")



[[ 1  2  3]
 [55 56  7]]
For inverse the martix should be square.


In [ ]:
#B.
import numpy as np
B = np.array(([1,2,3],
              [55,56,7],
              [6,7,12]))
print("The given Matrix is :\n", B)
B_inv = np.linalg.inv(A)
print("The inverse of the given matrix is:\n",B_inv)


The given Matrix is :
 [[ 1  2  3]
 [55 56  7]
 [ 6  7 12]]
The inverse of the given matrix is:
 [[-0.85576923 -0.78205128  0.25        0.38782051]
 [ 0.75        1.         -0.5        -0.25      ]
 [-0.08653846 -0.06410256  0.25       -0.09935897]
 [ 0.07692308 -0.12820513 -0.          0.05128205]]


In [ ]:
#C.
import numpy as np
C = np.array(([1,2,3,8],
              [5,6,7,5],
              [6,7,12,12],
              [11,12,13,20]))
print("The given Matrix is :\n", C)
C_inv = np.linalg.inv(A)
print("The inverse of the given matrix is:\n", C_inv)


The given Matrix is :
 [[ 1  2  3  8]
 [ 5  6  7  5]
 [ 6  7 12 12]
 [11 12 13 20]]
The inverse of the given matrix is:
 [[-0.85576923 -0.78205128  0.25        0.38782051]
 [ 0.75        1.         -0.5        -0.25      ]
 [-0.08653846 -0.06410256  0.25       -0.09935897]
 [ 0.07692308 -0.12820513 -0.          0.05128205]]


#Q.no.2.

In [ ]:
import numpy as np
arr = np.array([[5, 4, 3], 
                [6, -8, 7], 
                [1, -1, 10]])

inv_array = np.linalg.inv(arr)
print("Inverse array is:\n", inv_array)
print("The values of x1, x2, x3 are: ")
A= inverse_array
B = [[5],
    [15],
    [25]]
val = np.dot(A,B)
print(val)


Inverse array is:
 [[ 0.12784588  0.07530648 -0.0910683 ]
 [ 0.09281961 -0.08231173  0.02977233]
 [-0.00350263 -0.01576182  0.11208406]]
The values of x1, x2, x3 are: 
[[-0.50788091]
 [-0.0262697 ]
 [ 2.54816112]]


#Q.no.3.

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)



An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#Q.no.4.

In [ ]:
import numpy as np
m = np.array([[1, 2, 3],
              [55, 66, 7],
              [6, 7, 12]])
print("The Original square array:\n", m)
w, v = np.linalg.eig(m)
print("\nThe Eigen values of the given square array:\n", w)
print("The eigenvectors of the given square array:\n", v)


The Original square array:
 [[ 1  2  3]
 [55 66  7]
 [ 6  7 12]]

The Eigen values of the given square array:
 [68.81905127 -0.70229368 10.88324241]
The eigenvectors of the given square array:
 [[ 0.03480353  0.77221412  0.21267997]
 [ 0.99144253 -0.6351919  -0.32907749]
 [ 0.12581905 -0.01471714  0.92004089]]


#Q.no.5.

In [ ]:
import numpy as np
rand = np.random.normal(size=5)
print("The five random numbers from the normal distribution is ", rand)

The five random numbers from the normal distribution is  [ 1.44627438  0.25044499 -0.97438073 -0.76086584  0.2563406 ]


#Q.no.6.

In [ ]:
import numpy as np
rand = np.random.randint(low=10, high=30, size=6)
print("The six random numbers between 10 and 30 are:", rand)

The six random numbers between 10 and 30 are: [15 10 24 17 19 16]


#Q.no.7.

In [ ]:
import numpy as np
rand = np.random.random((3,3,3))
print("The 3*3*3 array or matrix with random values is: \n", rand)

The 3*3*3 array or matrix with random values is 
 [[[0.90118535 0.21799444 0.08909248]
  [0.82489178 0.22403095 0.15048744]
  [0.55611673 0.35648838 0.64598   ]]

 [[0.80669367 0.13485448 0.37986998]
  [0.7787065  0.77387699 0.79345898]
  [0.9689617  0.30798674 0.59317268]]

 [[0.76439442 0.41234494 0.88934263]
  [0.46885591 0.76978069 0.57108519]
  [0.72049899 0.49352508 0.08471412]]]


#Q.no.8.

In [ ]:
import numpy as np
a = np.random.random((5,5))
print("The original matrix is :\n", a)
amin, amax = a.min(), a.max()
print("The Minimun values and the Maximum values are:", amin,"and", amax)

The original matrix is :
 [[0.60419191 0.49405514 0.33574921 0.32599495 0.9402708 ]
 [0.79712124 0.18035434 0.03348734 0.16940295 0.41419378]
 [0.25807331 0.33131459 0.60490251 0.69851969 0.79825662]
 [0.56061784 0.66244612 0.70411708 0.16099339 0.6515691 ]
 [0.03890889 0.16148522 0.82932869 0.96976121 0.23111645]]
The Minimun values and the Maximum values are: 0.03348733750841548 and 0.9697612077386968


#Q.no.9.

In [ ]:
import numpy as np
a = np.random.random((3,3))
print("The original matrix is:\n", a)
amax = a.max()
amin = a.min()
a = (a-amin)/(amax-amin)
print("After normalization the 3*3 random matrix is:\n", a)

The original matrix is:
 [[0.4657901  0.24432174 0.53005109]
 [0.43600769 0.37378074 0.23671521]
 [0.57817496 0.91807851 0.50517438]]
After normalization the 3*3 random matrix is:
 [[0.3362008  0.0111637  0.43051318]
 [0.29249078 0.20116366 0.        ]
 [0.50114197 1.         0.39400298]]


#Q.no.10.

In [ ]:
import numpy as np
a = np.random.random(10)
print("The original matrix is:\n", a)
a.sort()
print("After sorting the original matrix become:\n",a)

The original matrix is:
 [0.45594029 0.72019254 0.48596867 0.58829418 0.14499318 0.12368872
 0.52390884 0.14089879 0.22597677 0.65884776]
After sorting the original matrix become:
 [0.12368872 0.14089879 0.14499318 0.22597677 0.45594029 0.48596867
 0.52390884 0.58829418 0.65884776 0.72019254]


#Q.no.11.

In [ ]:
import numpy as np
a = np.random.randint(0,4,7)
print("The First array:\n", a)
b = np.random.randint(0,4,7)
print("The second array:\n", b)
arr_equal = np.allclose(a, b)
print("Testing the above two random arrayes are equal or not:", arr_equal)

The First array:
 [2 1 2 0 3 2 1]
The second array:
 [3 2 1 3 2 1 0]
Testing the above two random arrayes are equal or not: False


#Q.no.12.

In [ ]:
import numpy as np
a = np.random.random(15)
print("The original matrix is :\n", a)
a[a.argmax()] = -1
print("After replacing the maximum value by -1 the resultant matrix is :\n", a)

The original matrix is :
 [0.35369601 0.91052843 0.1948748  0.70678144 0.1679593  0.79283306
 0.38468201 0.24797397 0.83710653 0.68509298 0.31114283 0.17098163
 0.38670761 0.99736779 0.07747831]
After replacing the maximum value by -1 the resultant matrix is :
 [ 0.35369601  0.91052843  0.1948748   0.70678144  0.1679593   0.79283306
  0.38468201  0.24797397  0.83710653  0.68509298  0.31114283  0.17098163
  0.38670761 -1.          0.07747831]


#Q.no.13.

In [ ]:
import numpy as np
a = np.array([[1,2],[11,12]])
print("The original matrix is:\n", a)
print("sorting the array along the first axis:")
print(np.sort(a, axis=0))
print("sorting the array along the last axis:")
print(np.sort(a))
print("Sorting the flattened array:")
print(np.sort(a, axis=None))

The original matrix is:
 [[ 1  2]
 [11 12]]
sorting the array along the first axis:
[[ 1  2]
 [11 12]]
sorting the array along the last axis:
[[ 1  2]
 [11 12]]
Sorting the flattened array:
[ 1  2 11 12]


#Q.no.14.

In [ ]:
import numpy as np
student_id = np.array([123, 126 , 140, 152])
student_height = np.array([145, 155, 165, 153])
#Sort by studen_id then by student_height
indices = np.lexsort((student_id, student_height))
print("Sorted indices:")
print(indices)
print("Sorted data:\nid   height")
for n in indices:
  print(student_id[n]," ", student_height[n])

Sorted indices:
[0 3 1 2]
Sorted data:
id   height
123   145
152   153
126   155
140   165


#Q.no.15.

In [ ]:
import numpy as np
X = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("The Original array:")
print(X)
indx = np.argsort(X)
print("Indices of the sorted elements of a given array:")
print(indx)


The Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


#Q.no.16.

In [ ]:
import numpy as np
complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
print("Given Original array:")
print(complex_num)
print("\nSorted a given complex array using the real part first and then the imaginary part.")
print(np.sort_complex(complex_num))


Given Original array:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

Sorted a given complex array using the real part first and then the imaginary part.
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


#Q.no.17.

In [ ]:
import numpy as np 
A = np.array([[1,2],
              [11,12],
              [12,15]])
print("MAtrix A:\n", A)
B = np.array([[1,2,3],
              [11,12,13]])
print("Matrix B:\n", B)
print("The product of Matrix A and the Matrix B is :\n",np.dot(A,B))

MAtrix A:
 [[ 1  2]
 [11 12]
 [12 15]]
Matrix B:
 [[ 1  2  3]
 [11 12 13]]
The product of Matrix A and the Matrix B is :
 [[ 23  26  29]
 [143 166 189]
 [177 204 231]]


#Q.no.18.

In [ ]:
import numpy as np
x = np.array([1., 5., 6., 9.], np.float32)
print("Original array: ")
print(x)
print("\ne^x, element-wise of the given array:")
r = np.exp(x)
print(r)


Original array: 
[1. 5. 6. 9.]

e^x, element-wise of the given array:
[2.7182820e+00 1.4841316e+02 4.0342877e+02 8.1030840e+03]


#Q.no.19

In [ ]:
import numpy as np
x = np.array([1, 2.5, 56, 19])
print("Given original array:\n", x)
print("Natural log =", np.log(x))
print("Common log =", np.log10(x))
print("Base 2 log =", np.log2(x))


Given original array:
 [ 1.   2.5 56.  19. ]
Natural log = [0.         0.91629073 4.02535169 2.94443898]
Common log = [0.         0.39794001 1.74818803 1.2787536 ]
Base 2 log = [0.         1.32192809 5.80735492 4.24792751]


#Q.no.20.

In [2]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nGiven Original array:\n", x)
a1 = np.ptp(x, 1)
a2 = np.amax(x, 1) - np.amin(x, 1)
assert np.allclose(a1, a2)
print("\nDifference between the maximum and the minimum values of the given array:")
print(a2)



Given Original array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Difference between the maximum and the minimum values of the given array:
[5 5]


#Q.no.21.

In [ ]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nGiven Original array:")
print(x)
r1 =  np.median(x)
print("\nMedian of the given array:")
print(r1)



Given Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Median of the given array:
5.5


#Q.no.22.

In [ ]:
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nGiven Original array1:")
print(x)
print("\nGiven Original array2:")
print(y)
print("\nCross-correlation of the two arrays:\n",np.cov(x, y))



Given Original array1:
[0 1 3]

Given Original array2:
[2 4 5]

Cross-correlation of the two arrays:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


#Q.no.23.

In [ ]:
import numpy as np
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 
print("Given Original array:")
print(array1)
print("Number of occurrences of each value in array: ")
print(np.bincount(array1))


Given Original array:
[0, 1, 6, 1, 4, 1, 2, 2, 7]
Number of occurrences of each value in array: 
[1 3 2 0 1 0 1 1]


#Q.no.24.

In [ ]:
import numpy as np
print("May, 2021")
print(np.arange('2021-05', '2021-06', dtype='datetime64[D]'))


May, 2021
['2021-05-01' '2021-05-02' '2021-05-03' '2021-05-04' '2021-05-05'
 '2021-05-06' '2021-05-07' '2021-05-08' '2021-05-09' '2021-05-10'
 '2021-05-11' '2021-05-12' '2021-05-13' '2021-05-14' '2021-05-15'
 '2021-05-16' '2021-05-17' '2021-05-18' '2021-05-19' '2021-05-20'
 '2021-05-21' '2021-05-22' '2021-05-23' '2021-05-24' '2021-05-25'
 '2021-05-26' '2021-05-27' '2021-05-28' '2021-05-29' '2021-05-30'
 '2021-05-31']


#Q.no.25.

In [ ]:
import numpy as np
A = np.array(['Python', 'PHP'], dtype=np.str)
B = np.array([' Java', ' C++'], dtype=np.str)
print("Array1:")
print(A)
print("Array2:")
print(B)
new_array = np.char.add(A, B)
print("tAfter the concatenation the new array:")
print(new_array)


Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
tAfter the concatenation the new array:
['Python Java' 'PHP C++']
